# Generated by Django 5.2.3 on 2025-12-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_negocio_pagamento_online_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendedorprofile',
            name='encrypted_access_token',
            field=models.CharField(blank=True, help_text='Token de acesso do Mercado Pago (Criptografado)', max_length=500, null=True),
        ),
    ]
