# Generated by Django 5.2.3 on 2025-12-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_empreendedorprofile_encrypted_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço físico do estabelecimento. Será usado para gerar o link do mapa.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='telefone_contato',
            field=models.CharField(blank=True, help_text='Telefone público para contato (WhatsApp). Diferente do telefone de login.', max_length=20, null=True),
        ),
    ]
