# Generated by Django 5.2.6 on 2025-12-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_negocio_endereco_negocio_telefone_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Aluguel', 'Aluguel'), ('Materiais', 'Materiais'), ('Serviços', 'Serviços'), ('Impostos', 'Impostos'), ('Salários', 'Salários'), ('Outros', 'Outros')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('dia_vencimento', models.IntegerField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ultima_geracao', models.DateField()),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.negocio')),
            ],
        ),
    ]
